name: Monitor Mods

on:
  push:
    paths:
      - 'Json/mods.json' # Avvia il workflow solo se viene modificato Json/mods.json
  workflow_dispatch: # Permette di avviare manualmente il workflow

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specifica la versione di Python

    - name: Install dependencies
      run: pip install requests python-telegram-bot==20.0

    - name: Run monitor script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GROUP_ID: '-1001771715212'
        TOPIC_ID: '79558'
        MODS_URL: 'https://raw.githubusercontent.com/MrNico98/HelpSimsSite/refs/heads/main/Json/mods.json'
        STATE_URL: 'https://raw.githubusercontent.com/MrNico98/HelpSimsSite/refs/heads/main/last_state.json'
        REPO_API_URL: 'https://api.github.com/repos/MrNico98/HelpSimsSite/contents/last_state.json'
      run: python app.py
